.\" Manpage for xcp-fe.
.\" Contact mike.mcclurg@citrix.com to correct errors or typos.
.TH man 1 "02 Dec 2011" "1.0" "xcp-fe man page"
.SH NAME
xcp-fe \- Forking-executioner daemon for XCP
.SH SYNOPSIS
.B xcp-fe
[\fI-daemon\fR] [\fI-pidfile filename\fR]
.SH DESCRIPTION
.HP
\fB\-daemon\fR Create a daemon
.TP
\fB\-pidfile\fR Set
the pid file (default "/var/run/fe.pid")
.TP
\fB\-help\fR
Display this list of options
.TP
\fB\-\-help\fR
Display this list of options
.SH "SEE ALSO"
xcp-xapi(1)
.SH BUGS
Probably ;) Please report bugs to the xen-api@lists.xensource.com mailing list.
.SH AUTHOR
Jonathan Ludlam <jonathan.ludlam@eu.citrix.com>
